---
abstract: 'Talk with Facebook'
author:
  - 'Jan Henning Thorsen - jhthorsen@cpan.org'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojo-Facebook
no_index:
  directory:
    - inc
    - t
requires:
  Mojolicious: 3.32
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Mojo-Facebook
  homepage: https://metacpan.org/release/Mojo::Facebook
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jhthorsen/mojo-facebook
version: 0.02
